# Generated by Django 4.1.7 on 2023-03-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fraud_App', '0002_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Image', models.ImageField(null=True, upload_to='images/')),
                ('Product_Name', models.CharField(default=None, max_length=100, null=True)),
                ('Product_Price', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
