# Generated by Django 4.1.7 on 2023-03-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fraud_App', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=None, max_length=100)),
                ('prod_id', models.CharField(default=None, max_length=100)),
                ('Prod_name', models.CharField(default=None, max_length=100)),
                ('Prod_price', models.CharField(default=None, max_length=100)),
                ('Prod_quantity', models.IntegerField(default=None, max_length=100)),
                ('Initial_price', models.CharField(default=None, max_length=100)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
