# Generated by Django 4.1.7 on 2023-03-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fraud_App', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Id', models.CharField(default=None, max_length=100, null=True)),
                ('ip_address', models.CharField(default=None, max_length=100, null=True)),
                ('City', models.CharField(default=None, max_length=100, null=True)),
                ('Spending', models.CharField(default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Transaction',
            },
        ),
    ]
