# Generated by Django 4.1.7 on 2023-03-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fraud_App', '0005_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='City',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='ip_address',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
