# Generated by Django 4.1.7 on 2023-04-03 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fraud_App', '0007_remove_transaction_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='City',
            new_name='Country',
        ),
    ]
