# Generated by Django 4.1.7 on 2023-04-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fraud_App', '0008_rename_city_userdetails_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Country',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
