# Generated by Django 4.1.7 on 2023-04-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fraud_App', '0010_transaction_fruad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Fruad',
            new_name='Fraud',
        ),
    ]
