# Generated by Django 4.1.7 on 2023-04-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fraud_App', '0012_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='Answer',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='Attempts',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='Question',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
