# Generated by Django 4.1.7 on 2023-04-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fraud_App', '0013_userdetails_answer_userdetails_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='Permission',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
