# Generated by Django 3.2.18 on 2023-04-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fraud_App', '0014_userdetails_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='OTP',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
